---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-spring
  namespace: chandan
  labels:
      app: try-spring
      env: testing
      partof: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try-spring
      env: testing
      partof: webserver
  template:
    metadata:
      labels:
        app: try-spring
        env: testing
        partof: webserver
    spec:
      containers:
      - name: try-spring
        image: gcr.io/trail-275304/try-spring:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 800Mi
          limits:
            cpu: 400m
            memory: 900Mi
        readinessProbe:
            httpGet:
                path: /
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
        livenessProbe:
            httpGet:
                path: /
                port: 8080
                httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 3
        ports:
            - name: http
              containerPort: 8080
