---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-spring
  namespace: chandan
  labels:
    app: try-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try-spring
  template:
    metadata:
      labels:
        app: try-spring
    spec:
      containers:
      - name: try-spring
        image: gcr.io/trail-275304/try-spring:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 400Mi
          limits:
            cpu: 300m
            memory: 400Mi
        readinessProbe:
            httpGet:
                path: /
                port: 8080
                scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
        ports:
            - name: http
              containerPort: 8080
