---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-spring
  namespace: chandan
  labels:
      app: try-spring
      env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try-spring
  template:
    metadata:
      labels:
        app: try-spring
        env: staging
    spec:
      containers:
      - name: try-spring
        image: gcr.io/trail-275304/try-spring:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 400Mi
        readinessProbe:
            httpGet:
                path: /try
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
        livenessProbe:
            httpGet:
                path: /try
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
        ports:
            - name: http
              containerPort: 8080
        env:
            - name: CONFIG_KEY1
              valueFrom:
                configMapKeyRef:
                    name: try-config
                    key: CONFIG_KEY1
            - name: CONFIG_KEY2
              valueFrom:
                configMapKeyRef:
                    name: try-config
                    key: CONFIG_KEY2
            - name: SECRET_KEY1
              valueFrom:
                secretKeyRef:
                    name: try-secret
                    key: SECRET_KEY1
            - name: SECRET_KEY2
              valueFrom:
                secretKeyRef:
                    name: try-secret
                    key: SECRET_KEY2
